services:
  cache:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - cache:/data
    networks:
      - backend
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lahlalmouad.it
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - backend
    ports:
      - 8080:80
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  cache:
    driver: local
  pgadmin:
    driver: local
  db:
    driver: local

networks:
  backend:
